#task 1

In [14]:
import numpy as np
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

#task 2

In [13]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#task 3

In [41]:
b = np.array([row[0] for row in a_centered])
c = np.array([row[1] for row in a_centered])
a_centered_sp = np.dot(b, c)
result = a_centered_sp/(len(a) - 1)
result

2.0

In [45]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])